const currencies = [
    {
        code: 'USD',
        name: 'Долар США',
        flag: require('./flags/us.png'),
    },
    {
        code: 'EUR',
        name: 'Євро',
        flag: require('./flags/eu.png'),
    },
    {
        code: 'GBP',
        name: 'Британський фунт',
        flag: require('./flags/gb.png'),
    },
    {
        code: 'UAH',
        name: 'Українська гривня',
        flag: require('./flags/ua.png'),
    },
    {
        code: 'PLN',
        name: 'Польський злотий',
        flag: require('./flags/pl.png'),
    },

    { code: 'AED', name: 'Дірхам ОАЕ', flag: null },
    { code: 'AFN', name: 'Афгані', flag: null },
    { code: 'ALL', name: 'Лек', flag: null },
    { code: 'AMD', name: 'Вірменський драм', flag: null },
    { code: 'ANG', name: 'Нідерландський антильський гульден', flag: null },
    { code: 'AOA', name: 'Кванза', flag: null },
    { code: 'ARS', name: 'Аргентинське песо', flag: null },
    { code: 'AUD', name: 'Австралійський долар', flag: null },
    { code: 'AWG', name: 'Арубський флорін', flag: null },
    { code: 'AZN', name: 'Азербайджанський манат', flag: null },
    { code: 'BAM', name: 'Конвертована марка', flag: null },
    { code: 'BBD', name: 'Барбадоський долар', flag: null },
    { code: 'BDT', name: 'Бангладешська така', flag: null },
    { code: 'BGN', name: 'Болгарський лев', flag: null },
    { code: 'BHD', name: 'Бахрейнський динар', flag: null },
    { code: 'BIF', name: 'Бурундійський франк', flag: null },
    { code: 'BMD', name: 'Бермудський долар', flag: null },
    { code: 'BND', name: 'Брунейський долар', flag: null },
    { code: 'BOB', name: 'Болівіано', flag: null },
    { code: 'BRL', name: 'Бразильський реал', flag: null },
    { code: 'BSD', name: 'Багамський долар', flag: null },
    { code: 'BTC', name: 'Біткоїн', flag: null },
    { code: 'BTN', name: 'Нгултрум', flag: null },
    { code: 'BWP', name: 'Пула (Ботсвана)', flag: null },
    { code: 'BYN', name: 'Білоруський рубль', flag: null },
    { code: 'BYR', name: 'Старий білоруський рубль', flag: null },
    { code: 'BZD', name: 'Белізький долар', flag: null },
    { code: 'CAD', name: 'Канадський долар', flag: null },
    { code: 'CDF', name: 'Конголезький франк', flag: null },
    { code: 'CHF', name: 'Швейцарський франк', flag: null },
    { code: 'CLF', name: 'Умовна розрахункова одиниця (CLF)', flag: null },
    { code: 'CLP', name: 'Чилійське песо', flag: null },
    { code: 'CNY', name: 'Китайський юань', flag: null },
    { code: 'CNH', name: 'Китайський юань (офшорний)', flag: null },
    { code: 'COP', name: 'Колумбійське песо', flag: null },
    { code: 'CRC', name: 'Костариканський колон', flag: null },
    { code: 'CUC', name: 'Конвертоване кубинське песо', flag: null },
    { code: 'CUP', name: 'Кубинське песо', flag: null },
    { code: 'CVE', name: 'Ескудо Кабо-Верде', flag: null },
    { code: 'CZK', name: 'Чеська крона', flag: null },
    { code: 'DJF', name: 'Джибутійський франк', flag: null },
    { code: 'DKK', name: 'Данська крона', flag: null },
    { code: 'DOP', name: 'Домініканське песо', flag: null },
    { code: 'DZD', name: 'Алжирський динар', flag: null },
    { code: 'EGP', name: 'Єгипетський фунт', flag: null },
    { code: 'ERN', name: 'Еритрейська накфа', flag: null },
    { code: 'ETB', name: 'Ефіопський бір', flag: null },
    { code: 'FJD', name: 'Долар Фіджі', flag: null },
    { code: 'FKP', name: 'Фунт Фолклендських островів', flag: null },
    { code: 'GEL', name: 'Грузинський ларі', flag: null },
    { code: 'GGP', name: 'Гернсійський фунт', flag: null },
    { code: 'GHS', name: 'Ґанський седі', flag: null },
    { code: 'GIP', name: 'Гібралтарський фунт', flag: null },
    { code: 'GMD', name: 'Даласі', flag: null },
    { code: 'GNF', name: 'Гвінейський франк', flag: null },
    { code: 'GTQ', name: 'Кетсаль', flag: null },
    { code: 'GYD', name: 'Гаянський долар', flag: null },
    { code: 'HKD', name: 'Гонконгський долар', flag: null },
    { code: 'HNL', name: 'Лемпіра', flag: null },
    { code: 'HRK', name: 'Хорватська куна', flag: null },
    { code: 'HTG', name: 'Гаїтянський гурд', flag: null },
    { code: 'HUF', name: 'Угорський форинт', flag: null },
    { code: 'IDR', name: 'Індонезійська рупія', flag: null },
    { code: 'ILS', name: 'Ізраїльський шекель', flag: null },
    { code: 'IMP', name: 'Фунт острова Мен', flag: null },
    { code: 'INR', name: 'Індійська рупія', flag: null },
    { code: 'IQD', name: 'Іракський динар', flag: null },
    { code: 'IRR', name: 'Іранський ріал', flag: null },
    { code: 'ISK', name: 'Ісландська крона', flag: null },
    { code: 'JEP', name: 'Фунт Джерсі', flag: null },
    { code: 'JMD', name: 'Ямайський долар', flag: null },
    { code: 'JOD', name: 'Йорданський динар', flag: null },
    { code: 'JPY', name: 'Японська єна', flag: null },
    { code: 'KES', name: 'Кенійський шилінг', flag: null },
    { code: 'KGS', name: 'Киргизький сом', flag: null },
    { code: 'KHR', name: 'Камбоджійський рієль', flag: null },
    { code: 'KMF', name: 'Коморський франк', flag: null },
    { code: 'KPW', name: 'Північнокорейський вон', flag: null },
    { code: 'KRW', name: 'Південнокорейський вон', flag: null },
    { code: 'KWD', name: 'Кувейтський динар', flag: null },
    { code: 'KYD', name: 'Долар Кайманових островів', flag: null },
    { code: 'KZT', name: 'Казахський тенге', flag: null },
    { code: 'LAK', name: 'Лаоський кіп', flag: null },
    { code: 'LBP', name: 'Ліванський фунт', flag: null },
    { code: 'LKR', name: 'Шрі-ланкійська рупія', flag: null },
    { code: 'LRD', name: 'Ліберійський долар', flag: null },
    { code: 'LSL', name: 'Лесотський лоті', flag: null },
    { code: 'LTL', name: 'Литовський літ', flag: null },
    { code: 'LVL', name: 'Латвійський лат', flag: null },
    { code: 'LYD', name: 'Лівійський динар', flag: null },
    { code: 'MAD', name: 'Марокканський дирхам', flag: null },
    { code: 'MDL', name: 'Молдовський лей', flag: null },
    { code: 'MGA', name: 'Малагасійський аріарі', flag: null },
    { code: 'MKD', name: 'Македонський денар', flag: null },
    { code: 'MMK', name: 'М\'янмський к\'ят', flag: null },
    { code: 'MNT', name: 'Монгольський тугрик', flag: null },
    { code: 'MOP', name: 'Патака Макао', flag: null },
    { code: 'MRO', name: 'Мавританська угія', flag: null },
    { code: 'MUR', name: 'Маврикійська рупія', flag: null },
    { code: 'MVR', name: 'Мальдівська руфія', flag: null },
    { code: 'MWK', name: 'Малавійська квача', flag: null },
    { code: 'MXN', name: 'Мексиканське песо', flag: null },
    { code: 'MYR', name: 'Малайзійський ринггіт', flag: null },
    { code: 'MZN', name: 'Мозамбіцький метикал', flag: null },
    { code: 'NAD', name: 'Намібійський долар', flag: null },
    { code: 'NGN', name: 'Нігерійська найра', flag: null },
    { code: 'NIO', name: 'Нікарагуанська кордоба', flag: null },
    { code: 'NOK', name: 'Норвезька крона', flag: null },
    { code: 'NPR', name: 'Непальська рупія', flag: null },
    { code: 'NZD', name: 'Новозеландський долар', flag: null },
    { code: 'OMR', name: 'Оманський ріал', flag: null },
    { code: 'PAB', name: 'Бальбоа', flag: null },
    { code: 'PEN', name: 'Перуанський соль', flag: null },
    { code: 'PGK', name: 'Папуа-новогвінейська кіна', flag: null },
    { code: 'PHP', name: 'Філіппінське песо', flag: null },
    { code: 'PKR', name: 'Пакистанська рупія', flag: null },
    { code: 'PYG', name: 'Парагвайський гуарані', flag: null },
    { code: 'QAR', name: 'Катарський ріал', flag: null },
    { code: 'RON', name: 'Румунський лей', flag: null },
    { code: 'RSD', name: 'Сербський динар', flag: null },
    { code: 'RUB', name: 'Російський рубль', flag: null },
    { code: 'RWF', name: 'Руандійський франк', flag: null },
    { code: 'SAR', name: 'Саудівський ріал', flag: null },
    { code: 'SBD', name: 'Долар Соломонових островів', flag: null },
    { code: 'SCR', name: 'Сейшельська рупія', flag: null },
    { code: 'SDG', name: 'Суданський фунт', flag: null },
    { code: 'SEK', name: 'Шведська крона', flag: null },
    { code: 'SGD', name: 'Сінгапурський долар', flag: null },
    { code: 'SHP', name: 'Фунт Святої Єлени', flag: null },
    { code: 'SLL', name: 'Леоне (Сьєрра-Леоне)', flag: null },
    { code: 'SOS', name: 'Сомалійський шилінг', flag: null },
    { code: 'SRD', name: 'Суринамський долар', flag: null },
    { code: 'STD', name: 'Добра (Сан-Томе і Принсіпі)', flag: null },
    { code: 'SYP', name: 'Сирійський фунт', flag: null },
    { code: 'SZL', name: 'Лілангені', flag: null },
    { code: 'THB', name: 'Тайський бат', flag: null },
    { code: 'TJS', name: 'Таджицький сомоні', flag: null },
    { code: 'TMT', name: 'Туркменський манат', flag: null },
    { code: 'TND', name: 'Туніський динар', flag: null },
    { code: 'TOP', name: 'Паанга (Тонга)', flag: null },
    { code: 'TRY', name: 'Турецька ліра', flag: null },
    { code: 'TTD', name: 'Долар Тринідаду і Тобаго', flag: null },
    { code: 'TWD', name: 'Новий тайванський долар', flag: null },
    { code: 'TZS', name: 'Танзанійський шилінг', flag: null },
    { code: 'UGX', name: 'Угандійський шилінг', flag: null },
    { code: 'UYU', name: 'Уругвайське песо', flag: null },
    { code: 'UZS', name: 'Узбецький сум', flag: null },
    { code: 'VEF', name: 'Венесуельський болівар', flag: null },
    { code: 'VND', name: 'В\'єтнамський донг', flag: null },
    { code: 'VUV', name: 'Вату (Вануату)', flag: null },
    { code: 'WST', name: 'Тала (Самоа)', flag: null },
    { code: 'XAF', name: 'Центральноафриканський франк CFA', flag: null },
    { code: 'XCD', name: 'Східнокарибський долар', flag: null },
    { code: 'XOF', name: 'Західноафриканський франк CFA', flag: null },
    { code: 'XPF', name: 'Французький тихоокеанський франк', flag: null },
    { code: 'YER', name: 'Єменський ріал', flag: null },
    { code: 'ZAR', name: 'Південноафриканський ранд', flag: null },
    { code: 'ZMK', name: 'Замбійська квача (стара)', flag: null },
    { code: 'ZMW', name: 'Замбійська квача', flag: null },
    { code: 'ZWL', name: 'Зімбабвійський долар', flag: null }
];

export default currencies;
